test/force-app/main/default/objects/Assumption_Set__c/Assumption_Set__c.object-meta.xml
<CustomObject>
    <label>Assumption Set</label>
    <nameField>
        <label>Assumption Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assumption Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

test/force-app/main/default/objects/Assumption_Set__c/fields/Annual_Insurance__c.field-meta.xml
<CustomField>
    <fullName>Annual_Insurance__c</fullName>
    <label>Insurance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

test/force-app/main/default/objects/Assumption_Set__c/fields/Availability__c.field-meta.xml
<CustomField>
    <fullName>Availability__c</fullName>
    <label>Availability</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

test/force-app/main/default/objects/Assumption_Set__c/fields/Class_A_Advance_Rate__c.field-meta.xml
<CustomField>
    <fullName>Class_A_Advance_Rate__c</fullName>
    <label>Class A Advance Rate</label>
    <precision>8</precision>
    <scale>5</scale>
    <type>Percent</type>
</CustomField>

test/force-app/main/default/objects/Assumption_Set__c/fields/Class_B_Target_PTIRR__c.field-meta.xml
<CustomField>
    <fullName>Class_B_Target_PTIRR__c</fullName>
    <label>Class B Target PTIRR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

test/force-app/main/default/objects/Assumption_Set__c/fields/Corporate_Overhead_W__c.field-meta.xml
<CustomField>
    <fullName>Corporate_Overhead_W__c</fullName>
    <label>Corporate Overhead ($/W)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

test/force-app/main/default/objects/Assumption_Set__c/fields/Development_Fee__c.field-meta.xml
<CustomField>
    <fullName>Development_Fee__c</fullName>
    <label>Development Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

test/force-app/main/default/objects/Assumption_Set__c/fields/Income_Available_Cash_Equity_post_flip__c.field-meta.xml
<CustomField>
    <fullName>Income_Available_Cash_Equity_post_flip__c</fullName>
    <label>Income Available (Cash Equity post-flip)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

test/force-app/main/default/objects/Assumption_Set__c/fields/Income_Available_Cash_Equity_pre_flip__c.field-meta.xml
<CustomField>
    <fullName>Income_Available_Cash_Equity_pre_flip__c</fullName>
    <description>Income Available for Allocation to Cash Equity (pre-flip)</description>
    <inlineHelpText>Income Available for Allocation to Cash Equity (pre-flip)</inlineHelpText>
    <label>Income Available  (Cash Equity pre-flip)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

test/force-app/main/default/objects/Assumption_Set__c/fields/Income_Available_Structured_Equity__c.field-meta.xml
<CustomField>
    <fullName>Income_Available_Structured_Equity__c</fullName>
    <description>Income Available for Allocation to Structured Equity</description>
    <inlineHelpText>Income Available for Allocation to Structured Equity</inlineHelpText>
    <label>Income Available (Structured Equity)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

test/force-app/main/default/objects/Assumption_Set__c/fields/Income_Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Income_Tax_Rate__c</fullName>
    <label>Income Tax Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

test/force-app/main/default/objects/Assumption_Set__c/fields/Insurance_Deflation__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Deflation__c</fullName>
    <label>Insurance Deflation</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

test/force-app/main/default/objects/Assumption_Set__c/fields/Inverter_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Inverter_Replacement_Cost__c</fullName>
    <label>Inverter Replacement Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

test/force-app/main/default/objects/Assumption_Set__c/fields/Inverter_Replacement_Freq__c.field-meta.xml
<CustomField>
    <fullName>Inverter_Replacement_Freq__c</fullName>
    <label>Inverter Replacement Frequency</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

test/force-app/main/default/objects/Assumption_Set__c/fields/Max_DRO__c.field-meta.xml
<CustomField>
    <fullName>Max_DRO__c</fullName>
    <label>Max DRO</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

test/force-app/main/default/objects/Assumption_Set__c/fields/Meter_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Meter_Replacement_Cost__c</fullName>
    <label>Meter Replacement Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

test/force-app/main/default/objects/Assumption_Set__c/fields/Meter_Replacement_Freq__c.field-meta.xml
<CustomField>
    <fullName>Meter_Replacement_Freq__c</fullName>
    <label>Meter Replacement Frequency</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

test/force-app/main/default/objects/Assumption_Set__c/fields/O_M_Escalator__c.field-meta.xml
<CustomField>
    <fullName>O_M_Escalator__c</fullName>
    <label>O&amp;M Escalator</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

test/force-app/main/default/objects/Assumption_Set__c/fields/PreFlip_Phase_I_Cash__c.field-meta.xml
<CustomField>
    <fullName>PreFlip_Phase_I_Cash__c</fullName>
    <label>Pre-Flip Phase I (Cash)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

test/force-app/main/default/objects/Assumption_Set__c/fields/PreFlip_Phase_I_Income__c.field-meta.xml
<CustomField>
    <fullName>PreFlip_Phase_I_Income__c</fullName>
    <label>Pre-Flip Phase I (Income)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

test/force-app/main/default/objects/Assumption_Set__c/fields/PreFlip_Phase_II_Cash__c.field-meta.xml
<CustomField>
    <fullName>PreFlip_Phase_II_Cash__c</fullName>
    <label>Pre-Flip Phase II (Cash)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

test/force-app/main/default/objects/Assumption_Set__c/fields/PreFlip_Phase_II_Income__c.field-meta.xml
<CustomField>
    <fullName>PreFlip_Phase_II_Income__c</fullName>
    <label>Pre-Flip Phase II (Income)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

test/force-app/main/default/objects/Assumption_Set__c/fields/PreFlip_Phase_III_Cash__c.field-meta.xml
<CustomField>
    <fullName>PreFlip_Phase_III_Cash__c</fullName>
    <label>Pre-Flip Phase III (Cash)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

test/force-app/main/default/objects/Assumption_Set__c/fields/PreFlip_Phase_III_Income__c.field-meta.xml
<CustomField>
    <fullName>PreFlip_Phase_III_Income__c</fullName>
    <label>Pre-Flip Phase III (Income)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

test/force-app/main/default/objects/Assumption_Set__c/fields/Project_level_Discount_Rate__c.field-meta.xml
<CustomField>
    <fullName>Project_level_Discount_Rate__c</fullName>
    <label>Project level Discount Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

test/force-app/main/default/objects/Assumption_Set__c/fields/Reduce_DRO_Postflip__c.field-meta.xml
<CustomField>
    <fullName>Reduce_DRO_Postflip__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reduce DRO Postflip</label>
    <type>Checkbox</type>
</CustomField>

test/force-app/main/default/objects/Assumption_Set__c/fields/Residual_Phase_Income__c.field-meta.xml
<CustomField>
    <fullName>Residual_Phase_Income__c</fullName>
    <label>Residual Phase (Income)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

test/force-app/main/default/objects/Assumption_Set__c/fields/Seasonality_Q1__c.field-meta.xml
<CustomField>
    <fullName>Seasonality_Q1__c</fullName>
    <label>Seasonality (Q1)</label>
    <precision>11</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

test/force-app/main/default/objects/Assumption_Set__c/fields/Seasonality_Q2__c.field-meta.xml
<CustomField>
    <fullName>Seasonality_Q2__c</fullName>
    <label>Seasonality (Q2)</label>
    <precision>11</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

test/force-app/main/default/objects/Assumption_Set__c/fields/Seasonality_Q3__c.field-meta.xml
<CustomField>
    <fullName>Seasonality_Q3__c</fullName>
    <label>Seasonality (Q3)</label>
    <precision>11</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

test/force-app/main/default/objects/Assumption_Set__c/fields/Seasonality_Q4__c.field-meta.xml
<CustomField>
    <fullName>Seasonality_Q4__c</fullName>
    <label>Seasonality (Q4)</label>
    <precision>11</precision>
    <scale>8</scale>
    <type>Percent</type>
</CustomField>

test/force-app/main/default/objects/Assumption_Set__c/fields/Target_Project_Rate_IRR__c.field-meta.xml
<CustomField>
    <fullName>Target_Project_Rate_IRR__c</fullName>
    <label>Target Project Rate IRR</label>
    <precision>15</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

test/force-app/main/default/objects/Merchant_Schedule__c/Merchant_Schedule__c.object-meta.xml
<CustomObject>
    <label>Merchant Schedule</label>
    <nameField>
        <displayFormat>MS{0000}</displayFormat>
        <label>Merchant Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Merchant Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

test/force-app/main/default/objects/Merchant_Schedule__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>17</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

test/force-app/main/default/objects/PortfolioFinancialAnalysis__c/PortfolioFinancialAnalysis__c.object-meta.xml
<CustomObject>
    <label>Financial Analysis</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Analysis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

test/force-app/main/default/objects/PortfolioFinancialAnalysis__c/fields/Assumption_Set__c.field-meta.xml
<CustomField>
    <fullName>Assumption_Set__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assumption Set</label>
    <referenceTo>Assumption_Set__c</referenceTo>
    <relationshipLabel>Financial Analysis</relationshipLabel>
    <relationshipName>Portfolios</relationshipName>
    <type>Lookup</type>
</CustomField>

test/force-app/main/default/objects/PortfolioFinancialAnalysis__c/fields/Estimated_COD__c.field-meta.xml
<CustomField>
    <fullName>Estimated_COD__c</fullName>
    <label>Estimated COD</label>
    <type>Date</type>
</CustomField>

test/force-app/main/default/objects/PortfolioFinancialAnalysis__c/fields/PPA_Escalator__c.field-meta.xml
<CustomField>
    <fullName>PPA_Escalator__c</fullName>
    <inlineHelpText>Please use your best estimate based on customer conversations/expectations, typically 0%, 1% or 2%.</inlineHelpText>
    <label>PPA Escalator</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

test/force-app/main/default/objects/PortfolioFinancialAnalysis__c/fields/PPA_Rate__c.field-meta.xml
<CustomField>
    <fullName>PPA_Rate__c</fullName>
    <label>PPA Rate</label>
    <precision>15</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

test/force-app/main/default/objects/PortfolioFinancialAnalysis__c/fields/PPA_Term__c.field-meta.xml
<CustomField>
    <fullName>PPA_Term__c</fullName>
    <inlineHelpText>Please use your best estimate based on customer conversations/expectations, typically 15, 20 or 25 years.</inlineHelpText>
    <label>PPA Term</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

test/force-app/main/default/objects/Sites__c/Sites__c.object-meta.xml
<CustomObject>
    <label>Sites</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

test/force-app/main/default/objects/Sites__c/fields/Class_A_Target_Flip__c.field-meta.xml
<CustomField>
    <fullName>Class_A_Target_Flip__c</fullName>
    <label>Class A Target Flip</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

test/force-app/main/default/objects/Sites__c/fields/Degradation__c.field-meta.xml
<CustomField>
    <fullName>Degradation__c</fullName>
    <label>Degradation</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

test/force-app/main/default/objects/Sites__c/fields/Development_Fee__c.field-meta.xml
<CustomField>
    <fullName>Development_Fee__c</fullName>
    <label>Development Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

test/force-app/main/default/objects/Sites__c/fields/EPC_Fee__c.field-meta.xml
<CustomField>
    <fullName>EPC_Fee__c</fullName>
    <label>EPC Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

test/force-app/main/default/objects/Sites__c/fields/ITC_Assumption__c.field-meta.xml
<CustomField>
    <fullName>ITC_Assumption__c</fullName>
    <label>ITC Assumption</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

test/force-app/main/default/objects/Sites__c/fields/Legal_Advisory_Transaction_Fees__c.field-meta.xml
<CustomField>
    <fullName>Legal_Advisory_Transaction_Fees__c</fullName>
    <label>Legal, Advisory &amp; Transaction Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

test/force-app/main/default/objects/Sites__c/fields/PPA_Term__c.field-meta.xml
<CustomField>
    <fullName>PPA_Term__c</fullName>
    <description>for portal project flow</description>
    <label>PPA Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

test/force-app/main/default/objects/Sites__c/fields/Project_level_Discount_Rate__c.field-meta.xml
<CustomField>
    <fullName>Project_level_Discount_Rate__c</fullName>
    <label>Project level Discount Rate</label>
    <precision>15</precision>
    <scale>5</scale>
    <type>Percent</type>
</CustomField>

test/force-app/main/default/objects/Sites__c/fields/Residual_Phase_Cash__c.field-meta.xml
<CustomField>
    <fullName>Residual_Phase_Cash__c</fullName>
    <label>Residual Phase (Cash)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

test/force-app/main/default/classes/FinancialAnalysisController_test.cls
@isTest //(SeeAllData=true)
public class FinancialAnalysisController_test {
    @TestSetup
    static void makeData(){
        
        Assumption_Set__c assumptionSet = new Assumption_Set__c(Name= 'AssumptionSet');          
        assumptionSet.Seasonality_Q1__c = 0.25;
        assumptionSet.Seasonality_Q2__c = 0.25;
        assumptionSet.Seasonality_Q3__c = 0.25;
        assumptionSet.Seasonality_Q4__c = 0.25;
        assumptionSet.Degradation__c = 0.5;
        assumptionSet.Class_A_Advance_Rate__c = 0.31942;
        assumptionSet.Income_Tax_Rate__c = 21;
        assumptionSet.PreFlip_Phase_I_Cash__c = 0.15;
        assumptionSet.PreFlip_Phase_II_Cash__c = 0.15;
        assumptionSet.PreFlip_Phase_III_Cash__c = 0.15;
        assumptionSet.Residual_Phase_Cash__c = 0.15;
        assumptionSet.PreFlip_Phase_I_Income__c = 0.15;
        assumptionSet.PreFlip_Phase_II_Income__c = 0.15;
        assumptionSet.PreFlip_Phase_III_Income__c = 0.15;
        assumptionSet.Residual_Phase_Income__c = 0.15;
        assumptionSet.Class_B_Target_PTIRR__c  = 0.15;
        assumptionSet.Max_DRO__c = 0.15;
        assumptionSet.Class_A_Target_Flip__c = 0.15;
        assumptionSet.Development_Fee__c = 15.0;
        assumptionSet.Legal_Advisory_Transaction_Fees__c = 0.15;
        assumptionSet.Availability__c = 0.15;
        assumptionSet.EPC_Fee__c = 0.15;
        assumptionSet.Corporate_Overhead_W__c = 0.15;
        assumptionSet.Annual_Insurance__c = 0.15;
        assumptionSet.Insurance_Deflation__c = 0.15;
        assumptionSet.Inverter_Replacement_Cost__c = 1000.0;
        assumptionSet.Inverter_Replacement_Freq__c = 11;
        assumptionSet.Meter_Replacement_Cost__c = 1000.0;
        assumptionSet.Meter_Replacement_Freq__c = 11;
        assumptionSet.O_M_Escalator__c = 0.15;
        assumptionSet.Income_Available_Cash_Equity_pre_flip__c = 0.15;
        assumptionSet.Income_Available_Cash_Equity_post_flip__c  = 0.15;
        assumptionSet.Income_Available_Structured_Equity__c = 0.15;
        assumptionSet.Reduce_DRO_Postflip__c = false;
        assumptionSet.Project_level_Discount_Rate__c = 6.75; 
        assumptionSet.Target_Project_Rate_IRR__c = 7.00;
        insert assumptionSet;

        PortfolioFinancialAnalysis__c analysis = new PortfolioFinancialAnalysis__c(Name= 'Analysis 1');
        analysis.Assumption_Set__c = assumptionSet.Id;
        
        analysis.Estimated_COD__c  = Date.today();
        analysis.PPA_Term__c = 20;
        analysis.PPA_Escalator__c = 2.0;
        analysis.ITC_Assumption__c = 2.0;
        analysis.PPA_Rate__c = 2.0;
        analysis.Model_Type_Solve_For__c = 'EPC Cost';
        insert analysis;     
        
        List<Sites__c> sites = new List<Sites__c>();
        for(Integer i=0;i<4;i++) {
            Sites__c site = new Sites__c(Name = 'Site'+i);
            site.Project__c = analysis.Id;
            site.Total_AC_Size__c = 575.0;
            site.Total_DC_Size__c = 766.2;
            site.Year_One_Specific_Yield__c = 1224.2;
            site.Number_of_Meters__c = 1;
            site.Transaction_Close__c = Date.today();
            site.PPA_Price__c = 0.043;
            site.Interconnection_Costs__c = 0.07; 
            site.Availability__c = 99.2;
            site.EPC_Cost__c = 2.0;
            site.EPC_Fee__c = 2.0;
            site.PPA_Term__c = 20;
            site.Project_Type__c =  'Canopy';
            site.Re_roofing_Fee__c=0.0;
            site.Property_Tax__c = 0.0;
            site.Other_Recurring_Expenses__c= 0.0;
            site.Property_Tax_Escalator__c= 0.0;
            site.Recurring_Expense_Escalator__c= 0.0;
            site.Annual_Lease_Escalator__c= 0.0;
            site.Annual_Lease_Payment__c= 0.0;
            sites.add(site);
        }
        insert sites;  

        Merchant_Schedule__c sched = new Merchant_Schedule__c();
        sched.Financial_Analysis__c = analysis.Id;
        sched.Fiscal_Year__c = Date.today();
        sched.Rate__c = 5.0;
        insert sched;
    }


    public static testmethod void testFinancialAnalysis() {
        PortfolioFinancialAnalysis__c financialAnalysis = [SELECT Id FROM PortfolioFinancialAnalysis__c WHERE Name = 'Analysis 1' LIMIT 1 ];
        ApexPages.currentPage().getParameters().put('id',financialAnalysis.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(financialAnalysis);

        FinancialAnalysisController controller = new FinancialAnalysisController(sc);

        Continuation conti = (Continuation)controller.runAnalysis();

        Map<String, HttpRequest> requests = conti.getRequests();
        system.assert(requests.size() == 3);

        List<Sites__c> siteIds = [SELECT Id from Sites__c LIMIT 4];


        String json = '{'+
		'    \"data\": {'+
		'        \"runAnalysis\": {'+
		'            \"success\": true,'+
		'            \"result\": {'+
		'                \"totalResults\": {'+
		'                    \"internalRateOfReturn\": 0.038578900141299055,'+
		'                    \"netPresentValue\": -1090908.658973364,'+
        '                    \"class_a_preflip_atirr\": 0.08221421898020354,'+
        '                    \"class_a_npv\": 77052.25799848778,'+
        '                    \"class_b_ptirr\": 0.07209624398058168,'+
        '                    \"class_b_npv\": -378123.2715412273'+
		'                },'+
		'                \"projectResults\": ['+
		'                    {'+
		'                        \"metadata\": {'+
		'                            \"name\": \"Site 1\",'+ 
		'                            \"identifier\": \"'+ String.valueOf(siteIds[0].Id)+ '\"'+
		'                        },'+
		'                        \"internalRateOfReturn\": 0.033006813869057794,'+
		'                        \"netPresentValue\": -197739.8988847947'+
		'                    },'+
		'                    {'+
		'                        \"metadata\": {'+
		'                            \"name\": \"Site 2\",'+
		'                            \"identifier\": \"'+ String.valueOf(siteIds[1].Id)+ '\"'+
		'                        },'+
		'                        \"internalRateOfReturn\": 0.03680393637261137,'+
		'                        \"netPresentValue\": -490470.1606569829'+
		'                    },'+
		'                    {'+
		'                        \"metadata\": {'+
		'                            \"name\": \"Site 3\",'+
		'                            \"identifier\": \"'+ String.valueOf(siteIds[2].Id)+ '\"'+
		'                        },'+
		'                        \"internalRateOfReturn\": 0.044958431970276935,'+
		'                        \"netPresentValue\": -146874.93011530765'+
		'                    },'+
		'                    {'+
		'                        \"metadata\": {'+
		'                            \"name\": \"Site 4\",'+
		'                            \"identifier\": \"'+ String.valueOf(siteIds[3].Id)+ '\"'+
		'                        },'+
		'                        \"internalRateOfReturn\": 0.040540210577644675,'+
		'                        \"netPresentValue\": -255823.66931627924'+
		'                    }'+
		'                ]'+
		'            }'+
		'        }'+
		'    }'+
		'}';

        String jsonPIRR = '{'+
		'  \"data\": {'+
		'    \"solve_for_portfolio_irr\": {'+
		'      \"success\": true,'+
		'      \"result\": {'+
		'        \"value\": 0.10259391326419223,'+
		'        \"variable\": \"PPA_RATE\"'+
		'      }'+
		'    }'+
		'  }'+
		'}';

        String jsonClassA = '{'+
        '    \"data\": {'+
        '      \"solve_for_class_a_advance\": {'+
        '        \"success\": true,'+
        '        \"result\": {'+
        '          \"value\": 0.3203270945662447,'+
        '          \"variable\": \"CLASS_A_ADVANCE\"'+
        '        }'+
        '      }'+
        '    }'+
        '  }';


        HttpResponse responseAnalysis = new HttpResponse();
        responseAnalysis.setStatusCode(200);
        responseAnalysis.setBody(json);
        Test.setContinuationResponse(controller.requestAnalysisLabel, responseAnalysis);

        HttpResponse solverClassAResponse = new HttpResponse();
        solverClassAResponse.setStatusCode(200);
        solverClassAResponse.setBody(jsonClassA);
        Test.setContinuationResponse(controller.requestClassALabel, solverClassAResponse);

        HttpResponse solverPIRRResponse = new HttpResponse();
        solverPIRRResponse.setStatusCode(200);
        solverPIRRResponse.setBody(jsonPIRR);
        Test.setContinuationResponse(controller.requestPIRRLabel, solverPIRRResponse);

        PageReference result = (PageReference)Test.invokeContinuationMethod(controller, conti);

        System.assertNotEquals(null, result);
        

    }

    public static testmethod void testSolver() {

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockModelResponseGenerator()); 
        
        PortfolioFinancialAnalysis__c financialAnalysis = [SELECT Id FROM PortfolioFinancialAnalysis__c WHERE Name = 'Analysis 1' LIMIT 1 ];

        ModelHelpers helper = new ModelHelpers(financialAnalysis.Id);        

      

       Double result = helper.solveForVariable('PPA Price');  
       Test.stopTest();
       System.assertNotEquals(null, result);

    }
}