test/force-app/main/default/objects/PortfolioFinancialAnalysis__c/PortfolioFinancialAnalysis__c.object-meta.xml
<CustomObject>
    <label>Financial Analysis</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Analysis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

test/force-app/main/default/objects/PortfolioFinancialAnalysis__c/fields/Customers_Partner__c.field-meta.xml
<CustomField>
    <fullName>Customers_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customers/Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Analysis</relationshipLabel>
    <relationshipName>Portfolios</relationshipName>
    <type>Lookup</type>
</CustomField>

test/force-app/main/default/classes/FinancialAnalysisTriggerHandler_Test.cls
@isTest
public class FinancialAnalysisTriggerHandler_Test {
    
    @testSetup
    static void setup() {
        Account testAccount = new Account(Name = 'Test Account 1234');
        insert testAccount;

        Contact testContact = new Contact(LastName = 'TestCon12345', AccountId = testAccount.id);
        insert testContact;

        User newUser1 = createPartnerUser(testContact.Id);
    }

    @isTest
    static void createShareRecords_Test() {
        Account testAccount = [SELECT Id FROM Account LIMIT 1];

        Test.startTest();
            PortfolioFinancialAnalysis__c testFinancialAnalysis = new PortfolioFinancialAnalysis__c(
                Name = 'Test Financial Analysis',
                Customers_Partner__c = testAccount.Id
            );

            insert testFinancialAnalysis;
        Test.stopTest();

        List<PortfolioFinancialAnalysis__Share> shareRecords = [SELECT Id FROM PortfolioFinancialAnalysis__Share];

        System.assert(shareRecords.size() == 1);
    }

    private static user createPartnerUser(Id contactId){
        Profile portalProfile = [
            SELECT Id, Name
            FROM Profile
            WHERE Name = 'DSD Partner User'
        ];

        User u = new User(
            UserName = 'test_' + Math.random() + '@test.com',
            FirstName = 'Test-First',
            LastName = 'Test-Last',
            Alias = 'test',
            email = 'test' + Math.random() + '@test.com',
            CommunityNickName = string.valueOf(Math.random()).substring(0,6),
            ProfileID = portalProfile.id,
            TimeZoneSidKey = 'America/New_York', 
            LocaleSidKey = 'en_US', 
            EmailEncodingKey = 'UTF-8', 
            LanguageLocaleKey = 'en_US',
            ContactID = contactId
        );

        insert u;

        return u;
    }
}