test/force-app/main/default/objects/PortfolioFinancialAnalysis__c/PortfolioFinancialAnalysis__c.object-meta.xml
<CustomObject>
    <label>Financial Analysis</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Analysis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

test/force-app/main/default/objects/PortfolioFinancialAnalysis__c/fields/Customers_Partner__c.field-meta.xml
<CustomField>
    <fullName>Customers_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customers/Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Analysis</relationshipLabel>
    <relationshipName>Portfolios</relationshipName>
    <type>Lookup</type>
</CustomField>

test/force-app/main/default/classes/FinancialAnalysisTriggerHelper.cls
public class FinancialAnalysisTriggerHelper {
    
    public static void shareRecordsWithPortalUsersOnTheSameAccount(List<PortfolioFinancialAnalysis__c> financialAnalysisList) {
        Map<Id, Account> partnerAccountMap;
        Map<Id, List<PortfolioFinancialAnalysis__c>> accountAndFinancialAnalysisMap = new Map<Id, List<PortfolioFinancialAnalysis__c>>();

        for(PortfolioFinancialAnalysis__c financialAnalysis : financialAnalysisList) {
            if(financialAnalysis.Customers_Partner__c != null) {
                if(!accountAndFinancialAnalysisMap.containsKey(financialAnalysis.Customers_Partner__c)) {
                    accountAndFinancialAnalysisMap.put(financialAnalysis.Customers_Partner__c, new List<PortfolioFinancialAnalysis__c>{financialAnalysis});
                } else {
                    List<PortfolioFinancialAnalysis__c> tempList = accountAndFinancialAnalysisMap.get(financialAnalysis.Customers_Partner__c);
                    tempList.add(financialAnalysis);
                    accountAndFinancialAnalysisMap.put(financialAnalysis.Customers_Partner__c, tempList);
                }
            }
        }

        try {
            partnerAccountMap = new Map<Id, Account>([
                SELECT Id,
                    (
                        SELECT Id
                        FROM Users
                    )
                FROM Account
                WHERE Id IN :accountAndFinancialAnalysisMap.keySet()
                AND IsPartner = true
            ]);
        } catch(Exception e) {
            partnerAccountMap = new Map<Id, Account>();
        }

        if(partnerAccountMap.size() > 0) {
            shareRecords(partnerAccountMap, accountAndFinancialAnalysisMap);
        }
    }

    private static void shareRecords(Map<Id, Account> partnerAccountMap, Map<Id, List<PortfolioFinancialAnalysis__c>> accountAndFinancialAnalysisMap) {
        List<PortfolioFinancialAnalysis__Share> shareRecordsList = new List<PortfolioFinancialAnalysis__Share>();

        for(Id accountId : partnerAccountMap.keySet()) {
            Account tempAccount = partnerAccountMap.get(accountId);
            
            if(tempAccount.Users != null && tempAccount.Users.size() > 0) {
                for(User tempUser : tempAccount.Users) {
                    List<PortfolioFinancialAnalysis__c> financialAnalysisList = accountAndFinancialAnalysisMap.get(accountId);

                    for(PortfolioFinancialAnalysis__c tempFinancialAnalysis : financialAnalysisList) {
                        if(tempFinancialAnalysis.OwnerId != tempUser.Id) {
                            shareRecordsList.add(
                                new PortfolioFinancialAnalysis__Share(
                                    AccessLevel = 'Edit',
                                    ParentId = tempFinancialAnalysis.Id,
                                    UserOrGroupId = tempUser.Id
                                )
                            );
                        }
                    }
                }
            }
        }

        if(shareRecordsList.size() > 0) {
            insert shareRecordsList;
        }
    }
}